Automatic backup

diff --git a/bin/autoiwyu b/bin/autoiwyu
--- a/bin/autoiwyu
+++ b/bin/autoiwyu
@@ -1,25 +1,44 @@
 #!/bin/fish
 
+if ! argparse "r/root-path=" "p/workdir=" -- $argv
+  exit "$status"
+end
+
 switch (count $argv)
   case 0
-    echo "Usage: $(status -f) COMMAND [ARGS...]" >&2
+    echo "Usage: $(status -f) COMMAND [ARGS...] --root-path=PATH [--workdir=PATH]" >&2
     exit 1
   case '*'
     set full_command $argv
 end
 
+if set --local --query _flag_root_path
+  set root_path "$_flag_root_path"
+else
+  echo "--root-path flag is required" >&2
+  exit 1
+end
+
 function main
   while true
     echo "Running '$full_command'..." >&2
-    $full_command &| process
+    fish --command "$full_command" &| process
     
-    test "$status" -eq 0 || return "$status"
-    test "$pipestatus[1]" -eq 0 || return 0
+    echo "$pipestatus" | read iwyu_status process_status
+    if test "$process_status" -ne 0
+      return 1
+    end
+    
+    if test "$iwyu_status" -eq 0
+      return 0
+    end
   end
 end
 
 function process
   while read line
+    echo "$line" >&2
+
     echo "$line" \
     | sed -E --quiet "s/^(.*) should (add|remove) these lines:\$/\1 \2/p" \
     | read source_path section_type
@@ -39,31 +58,49 @@ function process
         echo "Unknown section type '$section_type'" >&2
     end
 
-    test "$status" -eq 0 || return "$status"
+    test "$status" -eq 0 || return 1
   end
 end
 
 function process_addition -a source_path
+  set source_directory (basename "$source_path")
+
   while read line
     if test -z "$line"
       return 0
     end
 
+    echo "$line" \
+    | sed -E --quiet "s/^#include ([\"<])([^\"]+)[\">].*/\1 \2/p" \
+    | read enclosing_character include_path
+
+    switch "$enclosing_character"
+      case '<'
+        set fixed_include_path "$include_path"
+      case '"'
+        set fixed_include_path (
+          realpath --relative-to="$source_path" "$root_path/$include_path"
+        )
+      case '*'
+        echo "Warning: expecting an #include addition, got '$line'" >&2
+        continue
+    end
+
+    set include_path (string replace --all "/" "\/" "$include_path")
+    set fixed_include_path (string replace --all "/" "\/" "$fixed_include_path")
+
     set addition (
       echo "$line" \
+      | sed -E --quiet "s/$include_path/$fixed_include_path/p" \
       | sed -E --quiet "s/^(#include [\"<][^\"<>]+[\">]).*/\1/p" \
       | string replace --all "/" "\/"
     )
-    if test -z "$addition"
-      echo "Warning: expecting an #include addition, got '$line'" >&2
-      continue
-    end
 
     sed -E --in-place \
       "0,/^(#include .*)\$/s//$addition\n\1/" \
       "$source_path"
     
-    test "$status" -eq 0 || return "$status"
+    test "$status" -eq 0 || return 1
   end
 end
 
@@ -89,7 +126,7 @@ function process_removal -a source_path
       }" \
       "$source_path"
     
-    test "$status" -eq 0 || return "$status"
+    test "$status" -eq 0 || return 1
   end
 end
 
